id: 760d77d4080a4666be837de7939840f2
initial_creation_type: ocr
source_metadata:
  volumes:
    4ab27c8613cd44759f0dc8692311c859:
      base_file: v034.txt
      image_group_id: I1PD95879
      title: ''
      total_pages: 1734
      volume_number: 34
